language: go

go:
  - 1.13.x
  - master

os:
  - linux

jobs:
  allow_failures:
    - go: master

before_install:
  - go get -t -v ./...

script:
  - ./.ci/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - speakyourcode.com@gmail.com
    on_failure: always
